theme_graph <- function(base_size = 15, base_family = font_choose_graph, base_line_size = base_size/22, base_rect_size = base_size/22){
  
  half_line <- base_size/2
  
  theme(line = element_line(colour = "black", 
                            linewidth = base_line_size, 
                            linetype = 1, 
                            lineend = "butt"), 
        rect = element_rect(fill = "white", 
                            colour = "black", 
                            linewidth = base_rect_size, 
                            linetype = 1), 
        text = element_text(family = base_family, 
                            face = "plain", 
                            colour = "black", 
                            size = base_size, 
                            lineheight = 0.9, 
                            hjust = 0.5, vjust = 0.5, 
                            angle = 0, 
                            margin = margin(), 
                            debug = FALSE), 
        axis.line = element_line(), 
        axis.line.x = element_line(linewidth = 0.4),
        axis.line.y = element_blank(), 
        axis.text = element_text(size = rel(0.9), colour = "black"), 
        axis.text.x = element_text(margin = margin(t = 5, r = 0, b = 0, l = 0)),
        axis.text.x.top = element_text(margin = margin(b = 0.8 * half_line/2), vjust = 0), 
        axis.text.y = element_text(margin = margin(t = 0, r = 5, b = 0, l = 0), hjust = 1, vjust = 0.5), 
        axis.text.y.right = element_text(margin = margin(l = 0.8 * half_line/2), hjust = 0), 
        axis.ticks = element_line(), 
        axis.ticks.x = element_line(linewidth = 0.4),
        axis.ticks.y = element_line(linewidth = rel(0.5), colour = "#E8ECF1"),
        axis.ticks.length = unit(half_line/2, "pt"), 
        axis.title.x = element_text(size = base_size + 2, margin = margin(t = 7, r = 0, b = 0, l = 0), vjust = 1), 
        axis.title.x.top = element_text(margin = margin(b = half_line/2), vjust = 0), 
        axis.title.y = element_text(size = base_size + 2, angle = 90, margin = margin(t = 0, r = 7, b = 0, l = 0), vjust = 1), 
        axis.title.y.right = element_text(angle = -90, margin = margin(l = half_line/2), vjust = 0), 
        legend.background = element_rect(colour = NA), 
        legend.spacing = unit(2 * half_line, "pt"), 
        legend.spacing.x = NULL, 
        legend.spacing.y = NULL, 
        legend.margin = margin(half_line, half_line, half_line, half_line), 
        legend.key = element_blank(), 
        legend.key.size = unit(1.2, "lines"), 
        legend.key.height = NULL, 
        legend.key.width = NULL, 
        legend.text = element_text(size = rel(0.8)), 
        legend.text.align = NULL, 
        legend.title = element_text(hjust = 0), 
        legend.title.align = NULL, 
        legend.position = "top", 
        legend.direction = "horizontal", 
        legend.justification = "center", 
        legend.box = NULL, 
        legend.box.margin = margin(0, 0, 0, 0, "cm"), 
        legend.box.background = element_blank(), 
        legend.box.spacing = unit(2 * half_line, "pt"), 
        panel.background = element_blank(), 
        panel.border = element_blank(),
        panel.grid = element_line(colour = "#E8ECF1"), 
        panel.grid.major = element_line(linewidth = rel(0.5)), 
        panel.grid.minor = element_line(linewidth = rel(0.5)), 
        panel.grid.minor.x = element_blank(),
        panel.spacing = unit(half_line, "pt"), 
        panel.spacing.x = NULL, 
        panel.spacing.y = NULL, 
        panel.ontop = FALSE, 
        strip.background = element_rect(fill = "lightgrey", colour = "black"), 
        strip.text = element_text(colour = "black", size = rel(0.8), margin = margin(0.8 * half_line, 0.8 * half_line, 0.8 * half_line, 0.8 * half_line)), 
        strip.text.x = NULL, 
        strip.text.y = element_text(angle = -90), 
        strip.placement = "inside", 
        strip.placement.x = NULL, 
        strip.placement.y = NULL, 
        strip.switch.pad.grid = unit(half_line/2, "pt"), 
        strip.switch.pad.wrap = unit(half_line/2, "pt"), 
        plot.background = element_rect(colour = "white"), 
        plot.title = element_text(size = rel(1.2), hjust = 0, vjust = 1, margin = margin(b = half_line)), 
        plot.subtitle = element_text(hjust = 0, vjust = 1, margin = margin(b = half_line)), 
        plot.caption = element_text(size = rel(0.8), hjust = 1, vjust = 1, margin = margin(t = half_line)), 
        plot.tag = element_text(size = rel(1.2), hjust = 0.5, vjust = 0.5), 
        plot.tag.position = "topleft", 
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), 
        complete = TRUE)
}
