theme_map_area <- function(base_size = 14, base_family = font_choose_map, base_line_size = base_size/22, base_rect_size = base_size/22){
  
  half_line <- base_size/2
  
  theme(line = element_line(colour = "black", 
                            linewidth = base_line_size, 
                            linetype = 1, 
                            lineend = "butt"), 
        rect = element_rect(fill = "white", 
                            colour = "black", 
                            linewidth = base_rect_size, 
                            linetype = 1), 
        text = element_text(family = base_family, 
                            face = "plain", 
                            colour = "black", 
                            size = base_size, 
                            lineheight = 0.9, 
                            hjust = 0.5, vjust = 0.5, 
                            angle = 0, 
                            margin = margin(), 
                            debug = FALSE), 
        axis.line = element_blank(), 
        axis.line.x = NULL, 
        axis.line.y = NULL, 
        axis.text = element_text(color = "#2c3e50", size = 8),
        axis.text.x = element_text(margin = margin(t = 0.8 * half_line/2), vjust = 1),
        axis.text.x.top = element_text(margin = margin(b = 0.8 * half_line/2), vjust = 0),
        axis.text.y = element_text(margin = margin(r = 0.8 * half_line/2), hjust = 1),
        axis.text.y.right = element_text(margin = margin(l = 0.8 * half_line/2), hjust = 0),
        axis.ticks = element_line(color = "#2c3e50", linewidth = 0.25),
        axis.ticks.length = unit(4, "pt"),
        axis.title.x = element_blank(), 
        axis.title.x.top = element_text(margin = margin(b = half_line/2), vjust = 0), 
        axis.title.y = element_blank(), 
        axis.title.y.right = element_text(angle = -90, margin = margin(l = half_line/2), vjust = 0), 
        legend.background = element_rect(fill = "transparent", color = NA, linewidth = 0.25),
        legend.spacing = unit(2 * half_line, "pt"), 
        legend.spacing.x = NULL, 
        legend.spacing.y = NULL, 
        legend.margin = margin(half_line, half_line, half_line, half_line), 
        legend.key = element_rect(fill = "transparent", color = NA),
        legend.key.size = unit(1, "lines"), 
        legend.key.height = NULL, 
        legend.key.width = NULL, 
        legend.text = element_text(family = font_choose_map, size = 9, hjust = 0),
        legend.text.align = NULL, 
        legend.title = element_text(size = 10, face = "bold", color = "#2c3e50"),
        legend.position = "right", 
        legend.direction = "vertical", 
        legend.justification = "center", 
        legend.box = NULL, 
        legend.box.margin = margin(0, 0, 0, 0, "cm"), 
        legend.box.background = element_blank(),
        legend.box.spacing = unit(2 * half_line, "pt"), 
        panel.background = element_rect(fill = "#dff2f9", color = "#2c3e50", linewidth = 0.5),
        panel.border = element_rect(color = "#2c3e50", linewidth = 0.5, fill = NA),
        panel.grid = element_blank(),
        panel.grid.major = element_line(color = "#ecf0f1", linetype = "solid", linewidth = 0.25), 
        panel.grid.minor = element_blank(), 
        panel.spacing = unit(half_line, "pt"), 
        panel.spacing.x = NULL, 
        panel.spacing.y = NULL, 
        panel.ontop = FALSE, 
        strip.background = element_rect(fill = "transparent", color = NA), 
        strip.text = element_text(colour = "black", size = rel(0.8),
                                  margin = margin(0.8 * half_line, 0.8 * half_line, 0.8 * half_line, 0.8 * half_line)), 
        strip.text.x = NULL, 
        strip.text.y = element_text(angle = -90), 
        strip.placement = "inside", 
        strip.placement.x = NULL, 
        strip.placement.y = NULL, 
        strip.switch.pad.grid = unit(half_line/2, "pt"), 
        strip.switch.pad.wrap = unit(half_line/2, "pt"), 
        plot.background = element_blank(), 
        plot.title = element_text(size = rel(1.2), hjust = 0.5, vjust = 1, margin = margin(b = half_line)), 
        plot.subtitle = element_text(hjust = 0, vjust = 1, margin = margin(b = half_line)), 
        plot.caption = element_text(size = rel(0.8), hjust = 1, vjust = 1, margin = margin(t = half_line)), 
        plot.tag = element_text(size = rel(1.2), hjust = 0.5, vjust = 0.5), 
        plot.tag.position = "topleft", 
        plot.margin = margin(half_line, half_line, half_line, half_line),
        complete = TRUE)
}